### ISSUE TITLE
Unauthorized - getting no results

### ISSUE THREAD

**Issue by brianabbe** [daniel-centore/ParlerScraper#1]
Just got the scraper up and running and it seems I'm not able to get any posts.  Error message below.  Maybe there is something simple i'm doing wrong before I try to debug?

```
######################
### Scraping Seeds ###
######################
Scraping @CNN (seed)
    Fetching profile from API...
> API MESSAGE: Unauthorized
> Full json: {"message":"Unauthorized"}
> API REQUEST ATTEMPT 1 FAILED: API Message
> Endpoint: v1/profile?username=CNN
> Retrying in 1134ms...
> Retrying...
> API MESSAGE: Unauthorized
> Full json: {"message":"Unauthorized"}
> API REQUEST ATTEMPT 2 FAILED: API Message
> Endpoint: v1/profile?username=CNN
> Retrying in 2268ms...
> Retrying...
```

**Comment by daniel-centore** [comment]
I investigated and found a bug which caused it to ignore updates to the credentials in the UX (in addition to a second issue caused by a recent parler update which you would have run into afterward). Try pulling the latest version and trying again. If the problem persists with the latest version of the code then you probably have an issue with your `jst` or `mst`
